In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings

# machine learning
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Data


In [4]:
# import datasets
df = pd.read_csv('data/train.csv')


In [5]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
df.shape, 

((891, 12),)

# Sex

In [8]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [9]:
def transform_sex(n):
  if n == 'female':
    return 1
  else:
    return 0

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
# create a new colunm Sex_10
df['Sex_10'] = df['Sex'].map(transform_sex)

In [12]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_10  
0      0         A/5 21171   7.2500   NaN        S       0  
1      0          PC 17599  71.2833   C85        C       1  
2      0  STON/O2. 3101282   7.9250   NaN        S       1  
3      0            113803  53.1000  C123        S       1  
4      0            373450   8.0500   NaN        S       0

In [13]:
# colunm to train
variables = ['Sex_10', 'Age']

In [14]:
# Variable Survived to predict
X = df[variables]
y = df['Survived'] 

In [15]:
X.head()

Sex_10   Age
0       0  22.0
1       1  38.0
2       1  26.0
3       1  35.0
4       0  35.0

In [16]:
X = X.fillna(-1)

In [17]:
model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
model.fit(X, y)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [18]:
X_predict = df[variables]
X_predict = X_predict.fillna(-1)
X_predict.head()

Sex_10   Age
0       0  22.0
1       1  38.0
2       1  26.0
3       1  35.0
4       0  35.0

In [19]:
predict = model.predict(X_predict)
predict

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,

In [20]:
submission = pd.Series(predict, index = df['PassengerId'], name = 'Survived')
submission

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    1
888    1
889    1
890    0
891    0
Name: Survived, Length: 891, dtype: int64

In [21]:
submission.to_csv('first_model_sex.csv', header = True)

# Model 2

In [22]:
np.random.seed(0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50)

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape 


((445, 2), (446, 2), (445,), (446,))

In [24]:
#  Model
np.random.seed(0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50)

In [25]:
model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [26]:
p = model.predict(X_test)

In [27]:
# testing the accuracy
np.mean(y_test == p)

0.7690582959641256

In [28]:
p = (X_test['Sex_10'] == 1).astype(np.int64)
np.mean(y_test == p)

0.7825112107623319

# Cross-validation 1



In [29]:
results = []
for loop in range(10):
  print(f'Loop: {loop}')
  kf = KFold(2, shuffle=True, random_state=loop)

  for train_lines, test_lines in kf.split(X):
    print(f'Train: {train_lines.shape[0]}')
    print(f'Test: {test_lines.shape[0]}')

    X_train, X_test = X.iloc[train_lines], X.iloc[test_lines]
    y_train, y_test = y.iloc[train_lines], y.iloc[test_lines]

    model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
    model.fit(X_train, y_train)

    p = model.predict(X_test)

    accuracy = np.mean(y_test == p) 
    results.append(accuracy)
    print(f'Accuracy: {accuracy}')

Loop: 0
Train: 445
Test: 446
Accuracy: 0.7713004484304933
Train: 446
Test: 445
Accuracy: 0.7797752808988764
Loop: 1
Train: 445
Test: 446
Accuracy: 0.7443946188340808
Train: 446
Test: 445
Accuracy: 0.7955056179775281
Loop: 2
Train: 445
Test: 446
Accuracy: 0.7757847533632287
Train: 446
Test: 445
Accuracy: 0.7887640449438202
Loop: 3
Train: 445
Test: 446
Accuracy: 0.7533632286995515
Train: 446
Test: 445
Accuracy: 0.7573033707865169
Loop: 4
Train: 445
Test: 446
Accuracy: 0.7354260089686099
Train: 446
Test: 445
Accuracy: 0.7415730337078652
Loop: 5
Train: 445
Test: 446
Accuracy: 0.7219730941704036
Train: 446
Test: 445
Accuracy: 0.7056179775280899
Loop: 6
Train: 445
Test: 446
Accuracy: 0.7757847533632287
Train: 446
Test: 445
Accuracy: 0.7303370786516854
Loop: 7
Train: 445
Test: 446
Accuracy: 0.7040358744394619
Train: 446
Test: 445
Accuracy: 0.7348314606741573
Loop: 8
Train: 445
Test: 446
Accuracy: 0.7488789237668162
Train: 446
Test: 445
Accuracy: 0.7887640449438202
Loop: 9
Train: 445
Test: 446

In [30]:
 results

[0.7713004484304933,
 0.7797752808988764,
 0.7443946188340808,
 0.7955056179775281,
 0.7757847533632287,
 0.7887640449438202,
 0.7533632286995515,
 0.7573033707865169,
 0.7354260089686099,
 0.7415730337078652,
 0.7219730941704036,
 0.7056179775280899,
 0.7757847533632287,
 0.7303370786516854,
 0.7040358744394619,
 0.7348314606741573,
 0.7488789237668162,
 0.7887640449438202,
 0.7623318385650224,
 0.7842696629213484]

In [31]:
np.mean(results)

0.7550007557817302

# 2nd Cross Validation

In [32]:
results = []
kf = RepeatedKFold(n_splits=2, n_repeats=10, random_state=10)

for train_lines, test_lines in kf.split(X):
  print(f'Train: {train_lines.shape[0]}')
  print(f'Test: {test_lines.shape[0]}')

  X_train, X_test = X.iloc[train_lines], X.iloc[test_lines]
  y_train, y_test = y.iloc[train_lines], y.iloc[test_lines]

  model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
  model.fit(X_train, y_train)

  p = model.predict(X_test)

  accuracy = np.mean(y_test == p) 
  results.append(accuracy)
  print(f'Accuracy: {accuracy}')

Train: 445
Test: 446
Accuracy: 0.7511210762331838
Train: 446
Test: 445
Accuracy: 0.7617977528089888
Train: 445
Test: 446
Accuracy: 0.7533632286995515
Train: 446
Test: 445
Accuracy: 0.7595505617977528
Train: 445
Test: 446
Accuracy: 0.7690582959641256
Train: 446
Test: 445
Accuracy: 0.7573033707865169
Train: 445
Test: 446
Accuracy: 0.7399103139013453
Train: 446
Test: 445
Accuracy: 0.7595505617977528
Train: 445
Test: 446
Accuracy: 0.7354260089686099
Train: 446
Test: 445
Accuracy: 0.797752808988764
Train: 445
Test: 446
Accuracy: 0.7690582959641256
Train: 446
Test: 445
Accuracy: 0.7640449438202247
Train: 445
Test: 446
Accuracy: 0.7757847533632287
Train: 446
Test: 445
Accuracy: 0.7573033707865169
Train: 445
Test: 446
Accuracy: 0.7556053811659192
Train: 446
Test: 445
Accuracy: 0.7640449438202247
Train: 445
Test: 446
Accuracy: 0.7443946188340808
Train: 446
Test: 445
Accuracy: 0.7595505617977528
Train: 445
Test: 446
Accuracy: 0.7533632286995515
Train: 446
Test: 445
Accuracy: 0.7640449438202247


In [33]:
np.mean(results)

0.759601451100922

In [51]:
# Add more variables to analysis
variables = ['Sex_10', 'Age', 'Pclass', 'Fare']

In [52]:
X = df[variables].fillna(-1)
y = df['Survived']

In [53]:
X.head(10)

Sex_10   Age  Pclass     Fare
0       0  22.0       3   7.2500
1       1  38.0       1  71.2833
2       1  26.0       3   7.9250
3       1  35.0       1  53.1000
4       0  35.0       3   8.0500
5       0  -1.0       3   8.4583
6       0  54.0       1  51.8625
7       0   2.0       3  21.0750
8       1  27.0       3  11.1333
9       1  14.0       2  30.0708

In [37]:
results = []
kf = RepeatedKFold(n_splits=2, n_repeats=10, random_state=10)

for train_lines, test_lines in kf.split(X):
  print(f'Train: {train_lines.shape[0]}')
  print(f'Test: {test_lines.shape[0]}')

  X_train, X_test = X.iloc[train_lines], X.iloc[test_lines]
  y_train, y_test = y.iloc[train_lines], y.iloc[test_lines]

  model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
  model.fit(X_train, y_train)

  p = model.predict(X_test)

  accuracy = np.mean(y_test == p) 
  results.append(accuracy)
  print(f'Accuracy: {accuracy}')

Train: 445
Test: 446
Accuracy: 0.7869955156950673
Train: 446
Test: 445
Accuracy: 0.7797752808988764
Train: 445
Test: 446
Accuracy: 0.827354260089686
Train: 446
Test: 445
Accuracy: 0.8179775280898877
Train: 445
Test: 446
Accuracy: 0.7847533632286996
Train: 446
Test: 445
Accuracy: 0.7842696629213484
Train: 445
Test: 446
Accuracy: 0.8161434977578476
Train: 446
Test: 445
Accuracy: 0.7842696629213484
Train: 445
Test: 446
Accuracy: 0.8004484304932735
Train: 446
Test: 445
Accuracy: 0.8
Train: 445
Test: 446
Accuracy: 0.8183856502242153
Train: 446
Test: 445
Accuracy: 0.802247191011236
Train: 445
Test: 446
Accuracy: 0.8116591928251121
Train: 446
Test: 445
Accuracy: 0.8067415730337079
Train: 445
Test: 446
Accuracy: 0.820627802690583
Train: 446
Test: 445
Accuracy: 0.7887640449438202
Train: 445
Test: 446
Accuracy: 0.8385650224215246
Train: 446
Test: 445
Accuracy: 0.8044943820224719
Train: 445
Test: 446
Accuracy: 0.7982062780269058
Train: 446
Test: 445
Accuracy: 0.8112359550561797


In [38]:
results

[0.7869955156950673,
 0.7797752808988764,
 0.827354260089686,
 0.8179775280898877,
 0.7847533632286996,
 0.7842696629213484,
 0.8161434977578476,
 0.7842696629213484,
 0.8004484304932735,
 0.8,
 0.8183856502242153,
 0.802247191011236,
 0.8116591928251121,
 0.8067415730337079,
 0.820627802690583,
 0.7887640449438202,
 0.8385650224215246,
 0.8044943820224719,
 0.7982062780269058,
 0.8112359550561797]

In [54]:
np.mean(results)

0.8041457147175896

In [39]:
df[variables].head()

Sex_10   Age  Pclass  SibSp  Parch     Fare
0       0  22.0       3      1      0   7.2500
1       1  38.0       1      1      0  71.2833
2       1  26.0       3      0      0   7.9250
3       1  35.0       1      1      0  53.1000
4       0  35.0       3      0      0   8.0500

In [40]:
# Retrain the data to create a new sibmission
model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
model.fit(X, y)

p = model.predict(df[variables].fillna(-1))


In [41]:
p

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [42]:
submit = pd.Series(p, index = df['Fare'], name = 'Survived')
submit

Fare
7.2500     0
71.2833    1
7.9250     1
53.1000    1
8.0500     0
          ..
13.0000    0
30.0000    1
23.4500    0
30.0000    1
7.7500     0
Name: Survived, Length: 891, dtype: int64

# Logistic Regression

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [45]:
lr = LogisticRegression(max_iter = 2000)
cv = cross_val_score(lr,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.74166667 0.87394958 0.73109244 0.76470588 0.81512605]
0.7853081232492997


In [46]:
knn = KNeighborsClassifier()
cv = cross_val_score(knn,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.625      0.68067227 0.64705882 0.66386555 0.70588235]
0.6644957983193278


# Logistic regression: 78.%


# K Nearest Neighbour: 81.4%


# SVC:66.4% 